[colors.bright]
black = "#808080"
blue = "#0066ff"
cyan = "#00ffff"
green = "#33ff00"
magenta = "#cc00ff"
red = "#fe0100"
white = "#FFFFFF"
yellow = "#feff00"

[colors.cursor]
cursor = "#ffffff"
text = "#1E1E1E"

[colors.normal]
black = "#000000"
blue = "#0066ff"
cyan = "#00ffff"
green = "#33ff00"
magenta = "#cc00ff"
red = "#fe0100"
white = "#d0d0d0"
yellow = "#feff00"

[colors.primary]
background = "#1E1E1E"
foreground = "#ffffff"

[window.padding]
y = 10

[scrolling]
history = 10000
[font]
size = 11

[font.normal]
family = "JetBrainsMonoNerdFont"
style = "SemiBold"

[window]
opacity = 1.0

[mouse]
hide_when_typing = true

